name: Scroll sepolia Deployment

on:
  workflow_dispatch:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory ./blockchain

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - nmae: Deploy to scroll sepolia
        continue-on-error: false
        run: |
          forge create src/Counter.sol:Counter --rpc-url "https://sepolia-rpc.scroll.io/" --private-key ${{ secrets.SCROLL_SEPOLIA_PK }} --legacy
